# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  
jobs:
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: sudo lshw
      - run: echo "this is the build job"
      - run: echo "server throughput"
      - run: dd if=/dev/zero of=/tmp/test1.img bs=1G count=1 oflag=dsync
      - run: echo "server latency"
      - run: dd if=/dev/zero of=/tmp/test2.img bs=512 count=1000 oflag=dsync
      - run: echo "cpu"
      - run: cat /proc/cpuinfo | grep MHz
      - run: sudo apt update -y
      - run: sudo apt install -y sysbench && sysbench cpu --threads=4 run
      - run: sudo apt install -y p7zip-full
      - run: 7z b -mmt1
      - run: for i in {0001..2500}; do head -c 1M </dev/urandom >randfile$i; done
#      - run: time seq -w 1 100000 | xargs -n1 -I% sh -c 'dd if=/dev/urandom of=file.% bs=$(shuf -i1-10 -n1) count=1024'
  
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - test
